version: '3.8'

services:
  go-weather:
    container_name: go_weather
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
