name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  GCP_REGION: us-east1
  GCP_REPO_NAME: go-weather-iar
  IMAGE_NAME: go-weather
  SERVICE_NAME: go-weather

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        IMAGE: go-weather
        IMAGE_URI: us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/go-weather-iar/goweather:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup Google Cloud authentication
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{env.GCP_REGION}}-docker.pkg.dev

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{env.GCP_REGION}}-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t ${{env.GCP_REGION}}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.GCP_REPO_NAME }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA .

    - name: Push Docker image
      run: |
        docker push ${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.GCP_REPO_NAME }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA


    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image=${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.GCP_REPO_NAME }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA \
          --region=${{ env.GCP_REGION }} \
          --platform=managed \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --quiet \
          --allow-unauthenticated \
          --set-env-vars="
            GEOAPIFY_BASE_URL=${{ vars.GEOAPIFY_BASE_URL }},
            GEOAPIFY_API_KEY=${{ secrets.GEOAPIFY_API_KEY }},
            WEATHER_BASE_URL=${{ vars.WEATHER_BASE_URL }},
            WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}"
